### ISSUE TITLE
Unable to create Custom Kubernetes Resources

### ISSUE THREAD

**Issue by justinmchase** [Azure/bicep-extensibility#128]
Per this discussion https://github.com/Azure/bicep/discussions/10062 I am able to define a `apiextensions.k8s.io/CustomResourceDefinition` via the new kubernetes extension, but I am _unable_ to create a resource of the new custom type.

This is a very cool feature and it would be nice if this were possible.

If it were possible for this to translate into new resource types dynamically, that would be incredible but I'd settle for a clean way to add my own extension which simply defined the custom resources for bicep's sake.

**Comment by shenglol** [comment]
@alex-frankel reminded me of a simple workaround we can implement before we add the support for loading resource types dynamically from CRDs. If we fully qualify the CRD resource type with the kubernetes namespace, instead of generating an unrecognized resource type error, we can emit a warning instead, so that the Bicep file can be compiled. For example:

```Bicep
resource HelloWord 'kubernetes:example.com/Hello@v1' = { // warning: Unrecognized Kubernetes resource type.
  metadata: {
    name: 'hello-world'
  }
  spec: {
    name: 'World'
  }
}
```

**Comment by justinmchase** [comment]
That would be nice, would let me experiment

**Comment by shenglol** [comment]
@justinmchase Bicep v17.1 was published, and you should be able to use CRD now.
